version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY=`./awsom step ecr`
      - VERSION=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - docker build -t $REPOSITORY:$VERSION .
      - docker push $REPOSITORY:$VERSION
artifacts:
  files:
    - imageDetail.json